name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Configure kubectl
      run: |
        minikube status
        kubectl config view
        kubectl config current-context
        
    - name: Create Service Account
      run: |
        kubectl create serviceaccount terraform-sa || true
        kubectl create clusterrolebinding terraform-sa-binding \
          --clusterrole=cluster-admin \
          --serviceaccount=default:terraform-sa || true

    - name: Get Kubernetes Credentials
      run: |
        echo "KUBE_HOST=$(minikube ip)" >> $GITHUB_ENV
        echo "KUBE_CA_CERT=$(kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')" >> $GITHUB_ENV
        echo "KUBE_TOKEN=$(kubectl create token terraform-sa -n default)" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve \
          -var="host=https://${KUBE_HOST}:8443" \
          -var="token=${KUBE_TOKEN}" \
          -var="cluster_ca_certificate=${KUBE_CA_CERT}"